### ISSUE TITLE
[Dashboard] General information page

### ISSUE THREAD

**Issue by PhuongPhg** [chalalala/admin-template#25]
General information page:

1. General figures include:

- [x] Number of active users / total users
- [x] The total time the call was completed
- [x] User geographical distribution
- [x] The total amount of money spent over time
- [x] Total number of successful calls
- [x] Total amount of data used
- [x] Total loan amount
- [x] Total amount collected (after lending)
- [x] Total recharge amount (divided by card or virtual type)

2. Menu bar for detailed metrics:

- [ ] [Detailed information by users](#20 )
- [ ] [Detailed information by loan sales](#22 )
- [ ] [Details at recharge](#23 )
- [ ] [Detailed information by region, geographic area](#24 )

**Comment by PhuongPhg** [comment]
![image](https://user-images.githubusercontent.com/59214503/99544846-58447e00-29e7-11eb-81bd-a0b3707b4f2d.png)
![image](https://user-images.githubusercontent.com/59214503/99544869-5e3a5f00-29e7-11eb-9308-c4605dc0e6b1.png)
Only 1 data source
